### PR TITLE
Aggregate MaxFee calculation

### LINKED ISSUE #270: Aggregate bonded gets dropped due to incorrect max fee
With Aggregate bonded transaction its harder to calculate the min fee required for the transaction to get process.  The problem is due to the cosigner signatures is not included in the submission of the tx to the server.  The SDK has two proposals to fix this issue.

1) Use the multisig account graph as state by @evias.

What about using the multisig account graph to determine the _number of required_ signers ?

@Wayonb @fboucquez @rg911 http://api-01.us-west-1.symboldev.network:3000/account/TAWJ2M7BGKWGBPOUGD5NDKHYDDQ7OQD26HJMMQS2/multisig/graph

Knowing that aggregate bonded also have there own "announcement method". I can see this help because the account multisig *graph* can be iterated over to determine the needed *total* number of minApproval

_Originally posted by @evias in https://github.com/nemtech/symbol-sdk-java/issues/251#issuecomment-601109696_

This is gives an accurate min fee but has a lot of cost to figure out all the required cosigners.

2) Always calculate the max fee using the max cosigners as stated by @dgarcia360.

	One costly option for the users would be adding maxCosignaturesPerAggregate * cosignatureSize to the aggregate transaction size. Users can still pay fewer fees if they want to adjust better the cost by reducing the transaction's maxFee multiplier.

		MaxCosignaturesPerAggregate can be retrieved from https://github.com/nemtech/catapult-server/blob/master/resources/config-network.properties#L47

		This change requires to have a configuration parameter on the SDK to define which is the default maxCosingaturesPerAggregate since it might vary per network. The value could also be retrieved from REST if not specified.

### PR DESCRIPTION
**Pull request by fboucquez**
Calculating maxFee according to fee multiplier and maxConsignaures
Moved test resources to a commonplace avoiding duplicated
Fixed #270 #251. 

It follows the ts solution of https://github.com/nemtech/symbol-sdk-typescript-javascript/pull/539

### CODE REVIEW

File: sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/AggregateTransactionServiceImpl.java [hunk 1]
```diff
@@ -85,6 +90,35 @@ public AggregateTransactionServiceImpl(RepositoryFactory repositoryFactory) {
...
+    @Override
+    public Observable<Integer> getMaxCosignatures(Address address) {
+        return this.multisigRepository.getMultisigAccountGraphInfo(address)
+            .map(multisigAccountGraphInfo -> {
+                Stream<Address> publicAccountStream = multisigAccountGraphInfo
+                    .getMultisigAccounts().values().stream().flatMap(
+                        accounts -> accounts.stream()
+                            .flatMap(account -> account.getCosignatories().stream()
+                                .map(PublicAccount::getAddress)));
+                return (int) publicAccountStream.count();
```
Comment (fboucquez) [inline sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/AggregateTransactionServiceImpl.java:102]: @Wayonb @rg911 should we ignore duplicated cosigners that are on different levels? I guess because they are different signatures for the same cosigner duplicated must be counted

File: sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AggregateTransactionFactory.java [hunk 2]
```diff
@@ -108,6 +109,41 @@ public static AggregateTransactionFactory createComplete(NetworkType networkType
...
+     *
+     * Because the factory creates an aggregate transcation, an {@link IllegalArgumentException} is
+     * raised. users should not use this method.
+     *
+     * @param feeMultiplier the fee multiplier greater than 1
+     * @return raises a IllegalArgumentException
+     */
+    public AggregateTransactionFactory calculateMaxFeeFromMultiplier(int feeMultiplier) {
+        throw new IllegalArgumentException(
+            "calculateMaxFeeFromMultiplier can only be used for none aggregate transactions.");
```
Comment (Wayonb) [inline sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AggregateTransactionFactory.java:123]: non-aggregate

File: sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AggregateTransactionFactory.java [hunk 3]
```diff
@@ -108,6 +109,41 @@ public static AggregateTransactionFactory createComplete(NetworkType networkType
...
+     * @param requiredCosignatures Required number of cosignatures
+     * @return The aggregate transaction factory
+     */
+    public AggregateTransactionFactory calculateMaxFeeForAggregate(int feeMultiplier,
+        int requiredCosignatures) {
+        // Check if current cosignature count is greater than requiredCosignatures.
+        int calculatedCosignatures = Math.max(this.cosignatures.size(), requiredCosignatures);
+        // Remove current cosignature length and use the calculated one.
+        int calculatedSize =
+            this.getSize() - this.cosignatures.size() * 96 + calculatedCosignatures * 96;
```
Comment (Wayonb) [inline sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AggregateTransactionFactory.java:142]: minor change:
int calculatedSize =
            this.getSize() + (calculatedCosignatures - this.cosignatures.size()) * 96;

File: sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/AggregateTransactionServiceImpl.java (hunk 1 above)
Comment (fboucquez) [reply sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/AggregateTransactionServiceImpl.java:102]: @Wayonb getMaxCosignatures should return non duplicated addresses count right?

Comment (Wayonb) [reply sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/AggregateTransactionServiceImpl.java]: @fboucquez Yes, no duplicate address.

Comment (fboucquez) [reply sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/AggregateTransactionServiceImpl.java]: Ok, so the mutlsign definition may have duplicated accounts by the signed transaction won't have duplicated signers. (The fee would be lower) Cool.
